function [Rba,M] = Rotations(in1)
%ROTATIONS
%    [RBA,M] = ROTATIONS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    28-Jan-2020 12:50:13

psi = in1(3,:);
rho = in1(1,:);
theta = in1(2,:);
t2 = cos(theta);
t3 = sin(psi);
t4 = cos(psi);
t5 = sin(theta);
t6 = cos(rho);
t7 = sin(rho);
t8 = t3.*t7;
t19 = t4.*t5.*t6;
t9 = t8-t19;
t10 = t4.*t7;
t11 = t3.*t5.*t6;
t12 = t10+t11;
t13 = t2.^2;
t14 = t4.*t6;
t20 = t3.*t5.*t7;
t15 = t14-t20;
t16 = t3.*t6;
t17 = t4.*t5.*t7;
t18 = t16+t17;
Rba = reshape([t2.*t4,t18,t9,-t2.*t3,t15,t12,t5,-t2.*t7,t2.*t6],[3,3]);
if nargout > 1
    M = reshape([t2.*t5.*t6+t2.*t4.*t9-t2.*t3.*t12,0.0,0.0,-t5.^2.*t7-t3.^2.*t7.*t13-t4.^2.*t7.*t13,t6.*t13-t4.*t5.*t9+t3.*t5.*t12,t7.*t13-t3.*t5.*t15+t4.*t5.*t18,-t2.*t4.*t15-t2.*t3.*t18,-t2.*t3.*t9-t2.*t4.*t12,t2.*t4.*t15+t2.*t3.*t18],[3,3]);
end
