function [Rot,M] = Rotations3(in1)
%ROTATIONS3
%    [ROT,M] = ROTATIONS3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    26-Jan-2020 19:34:23

phi = in1(1,:);
psi = in1(3,:);
theta = in1(2,:);
t2 = sin(psi);
t3 = cos(psi);
t4 = sin(theta);
t5 = cos(theta);
t6 = sin(phi);
t7 = cos(phi);
t8 = t3.*t7;
Rot = reshape([t3.*t5-t2.*t4.*t6,t2.*t5+t3.*t4.*t6,-t4.*t7,-t2.*t7,t8,t6,t3.*t4+t2.*t5.*t6,t2.*t4-t3.*t5.*t6,t5.*t7],[3, 3]);
if nargout > 1
    M = reshape([t3,t2,0.0,-t2.*t7,t8,t6,0.0,0.0,1.0],[3, 3]);
end
