function [Rot,M] = Rotations(in1)
%ROTATIONS
%    [ROT,M] = ROTATIONS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    26-Jan-2020 18:09:09

phi = in1(1,:);
psi = in1(3,:);
theta = in1(2,:);
t2 = cos(psi);
t3 = sin(phi);
t4 = sin(psi);
t5 = cos(phi);
t6 = sin(theta);
t7 = cos(theta);
t8 = t2.*t7;
t9 = t4.*t7;
Rot = reshape([t8,t9,-t6,-t4.*t5+t2.*t3.*t6,t2.*t5+t3.*t4.*t6,t3.*t7,t3.*t4+t2.*t5.*t6,-t2.*t3+t4.*t5.*t6,t5.*t7],[3, 3]);
if nargout > 1
    M = reshape([t8,t9,-t6,-t4,t2,0.0,0.0,0.0,1.0],[3, 3]);
end
