function [W,RHS] = BallAndBeamODEMatrices(in1,To,in3)
%BALLANDBEAMODEMATRICES
%    [W,RHS] = BALLANDBEAMODEMATRICES(IN1,TO,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-Feb-2020 15:00:57

J = in3(1,:);
M = in3(2,:);
R = in3(3,:);
dtheta = in1(4,:);
g = in3(4,:);
theta = in1(2,:);
x = in1(1,:);
W = reshape([M,-M.*R,-M.*R,J+M.*R.^2+M.*x.^2],[2,2]);
if nargout > 1
    RHS = [-M.*(dtheta.^2.*x+g.*sin(theta));To./J-M.*g.*x.*cos(theta)];
end
