function [W,RHS] = PendulumODEMatrices(in1,F,in3)
%PENDULUMODEMATRICES
%    [W,RHS] = PENDULUMODEMATRICES(IN1,F,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-Feb-2020 11:36:33

L = in3(3,:);
M = in3(2,:);
dtheta1 = in1(5,:);
dtheta2 = in1(6,:);
dx = in1(4,:);
g = in3(4,:);
m = in3(1,:);
theta1 = in1(2,:);
theta2 = in1(3,:);
x = in1(1,:);
t2 = cos(theta1);
t3 = M.*t2.*2.0;
t4 = sin(theta1);
t5 = t4.^2;
t6 = cos(theta2);
t7 = L.^2;
t8 = M.*t6;
t9 = sin(theta2);
t10 = t9.^2;
W = reshape([M.*2.0+m,t3,t8,t3,M.*(t5.*-2.0+t5.*t7.*2.0+2.0),M.*t2.*t6+M.*t4.*t7.*t9,t8,M.*(t2.*t6+t4.*t7.*t9),M.*(-t10+t7.*t10+1.0)],[3,3]);
if nargout > 1
    t11 = dtheta1.^2;
    t12 = theta1.*2.0;
    t13 = sin(t12);
    t14 = dtheta2.^2;
    t15 = theta2.*2.0;
    t16 = sin(t15);
    RHS = [-dx-x.*1.0e1;M.*(t11.*t13-L.*g.*t4.*2.0+dtheta1.*dx.*t4.*2.0-t7.*t11.*t13+dtheta1.*dtheta2.*t4.*t6-dtheta1.*dtheta2.*t2.*t7.*t9);M.*((t14.*t16)./2.0-L.*g.*t9+dtheta2.*dx.*t9-(t7.*t14.*t16)./2.0+dtheta1.*dtheta2.*t2.*t9-dtheta1.*dtheta2.*t4.*t6.*t7)];
end
