function [W,RHS] = PendulumODEMatrices(in1,F,in3)
%PENDULUMODEMATRICES
%    [W,RHS] = PENDULUMODEMATRICES(IN1,F,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-Feb-2020 11:49:27

L = in3(3,:);
M = in3(2,:);
dtheta1 = in1(5,:);
dtheta2 = in1(6,:);
dx = in1(4,:);
g = in3(4,:);
m = in3(1,:);
theta1 = in1(2,:);
theta2 = in1(3,:);
t2 = cos(theta1);
t3 = M.*t2.*2.0;
t4 = t2.^2;
t5 = L.^2;
t6 = cos(theta2);
t7 = M.*t6;
t8 = t2.*t6;
t9 = sin(theta1);
t10 = sin(theta2);
t11 = t5.*t9.*t10;
t12 = t8+t11;
t13 = M.*t12;
t14 = t6.^2;
W = reshape([M.*2.0+m,t3,t7,t3,M.*(t4.*2.0+t5.*2.0-t4.*t5.*2.0),t13,t7,t13,M.*(t5+t14-t5.*t14)],[3,3]);
if nargout > 1
    t15 = dtheta1.^2;
    t16 = theta1.*2.0;
    t17 = sin(t16);
    t18 = dtheta2.^2;
    t19 = theta2.*2.0;
    t20 = sin(t19);
    RHS = [F;M.*(t15.*t17-L.*g.*t9.*2.0+dtheta1.*dx.*t9.*2.0-t5.*t15.*t17+dtheta1.*dtheta2.*t6.*t9-dtheta1.*dtheta2.*t2.*t5.*t10);M.*((t18.*t20)./2.0-L.*g.*t10+dtheta2.*dx.*t10-(t5.*t18.*t20)./2.0+dtheta1.*dtheta2.*t2.*t10-dtheta1.*dtheta2.*t5.*t6.*t9)];
end
